---
version: "2"
services:
  smokeping:
    image: linuxserver/smokeping
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Central
    volumes:
      - ./enter/config/location/here:/config
      - ./smokeping/data:/data
      - ./smokeping/etc/config:/etc/smokeping/config
      - ./smokeping/etc/ssmtp.conf:/etc/ssmtp/ssmtp.conf
    ports:
      - 82:80
    mem_limit: 4096m
    restart: always
